#!/usr/bin/python 

import os
import sys
import re
import glob
import string

# list of tests to run ...

standard_tests = ['cmd', 'chempy']

# set module path for generic python stuff

ppath = ''
if os.environ.has_key('PYTHONPATH'):
   ppath = os.environ['PYTHONPATH']
ppath = ppath + ":" + os.getcwd() + "/../modules"

os.environ['PYTHONPATH'] = ppath

# uniform parameter handling

argv = sys.argv

if len(argv):
   if re.search("\.py$",argv[0]):
      argv = argv[1:]

# ---

pymol = "pymol"
cmp = "cmp"
ref = "ref"
inp = "inp"
if not os.path.exists(cmp):
   os.mkdir(cmp)

if len(argv):
   tests = argv
else:
   tests = standard_tests

for test in tests:
   for ifil in glob.glob( inp+"/"+test+"*" ):
      f = open(ifil) # get command for running test
      cmd = f.readline()
      f.close()
      cmd = string.strip(re.sub(r"^#*","",cmd))
      tst = re.sub(r".*/","",ifil) # get exact test name
      tst = re.sub(r"\..*","",tst)
      print " show_tests: "+tst+"..."
      os.system(cmd+" "+ifil)



