target_sources(
  ${TARGET_NAME}
  PRIVATE ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/abinitplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/avsplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/basissetplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/bgfplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/binposplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/biomoccaplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/brixplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/carplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/ccp4plugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/corplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/crdplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/cubeplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/dcdplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/dlpolyplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/dsn6plugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/dtrplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/dxplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/edmplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/fs4plugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/gamessplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/graspplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/grdplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/gridplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/gromacsplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/hash.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/inthash.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/jsplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/maeffplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/mapplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/mdfplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/mol2plugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/moldenplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/molemeshplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/msmsplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/namdbinplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/netcdfplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/offplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/parm7plugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/parmplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/pbeqplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/pdbplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/pdbxplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/phiplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/pltplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/PlugIOManagerInit.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/plyplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/pqrplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/psfplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/raster3dplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/rst7plugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/situsplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/spiderplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/stlplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/tinkerplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/uhbdplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vasp5xdatcarplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vaspchgcarplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vaspoutcarplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vaspparchgplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vaspposcarplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vaspxdatcarplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vaspxmlplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vtfplugin.c
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/vtkplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/xbgfplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/xsfplugin.cpp
          ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/xyzplugin.c)

target_include_directories(
  ${TARGET_NAME} PUBLIC ${CMAKE_CURRENT_LIST_DIR}/include
                        ${CMAKE_CURRENT_LIST_DIR}/molfile_plugin/src/)
