if(NOT PYMOL_GLUT)
  list(APPEND PYMOL_DEF_MACROS "_PYMOL_NO_MAIN")
endif()

find_package(GLEW REQUIRED)
list(APPEND PYMOL_LIBS GLEW::GLEW)

if(APPLE)
  if(PYMOL_OSX_FRAMEWORKS)
    list(APPEND PYMOL_LINK_OPTIONS "-framework OpenGL")
    if(GLUT)
      list(APPEND PYMOL_LINK_OPTIONS "-framework GLUT")
    endif()
    list(APPEND PYMOL_DEF_MACROS "_PYMOL_OSX")
  else()
    list(APPEND PYMOL_LIBS "GL")
    if(GLUT)
      list(APPEND PYMOL_LIBS "glut")
    endif()
  endif()

elseif(WIN32)
  list(APPEND PYMOL_LIBS "Advapi32" "Ws2_32" "opengl32")

  if(PYMOL_GLUT)
    list(APPEND PYMOL_LIBS "freeglut")
  endif()

else()
  list(APPEND PYMOL_LIBS "GL")
  if(GLUT)
    list(APPEND PYMOL_LIBS "glut")
  endif()
endif()
