
# BEGIN PROPRIETARY CODE SEGMENT (see disclaimer in "os_proprietary.h") 

all: library

include ../../../../../Rules.delsci
include objects.make

CFLAGS=-I../../include -I. $(CCOPT2)
CXXFLAGS=-I../../include -I. $(CCOPT2)
# CPPFLAGS=-I../../include $(CCOPT2)

library: $(OBJS) PlugIOManagerInit.o

static: $(DEPS) $(OBJS)

clean:
	/bin/rm -f *.o 

# END PROPRIETARY CODE SEGMENT 
