/* MACHINE GENERATED FILE, DO NOT EDIT! */

#include "vmdplugin.h"

typedef struct _PyMOLGlobals PyMOLGlobals;
/* prototypes */int molfile_avsplugin_init(void);
int molfile_avsplugin_register(void *,vmdplugin_register_cb);
int molfile_avsplugin_fini(void);
int molfile_basissetplugin_init(void);
int molfile_basissetplugin_register(void *,vmdplugin_register_cb);
int molfile_basissetplugin_fini(void);
int molfile_basissetplugin_init(void);
int molfile_basissetplugin_register(void *,vmdplugin_register_cb);
int molfile_basissetplugin_fini(void);
int molfile_bgfplugin_init(void);
int molfile_bgfplugin_register(void *,vmdplugin_register_cb);
int molfile_bgfplugin_fini(void);
int molfile_binposplugin_init(void);
int molfile_binposplugin_register(void *,vmdplugin_register_cb);
int molfile_binposplugin_fini(void);
int molfile_biomoccaplugin_init(void);
int molfile_biomoccaplugin_register(void *,vmdplugin_register_cb);
int molfile_biomoccaplugin_fini(void);
int molfile_brixplugin_init(void);
int molfile_brixplugin_register(void *,vmdplugin_register_cb);
int molfile_brixplugin_fini(void);
int molfile_carplugin_init(void);
int molfile_carplugin_register(void *,vmdplugin_register_cb);
int molfile_carplugin_fini(void);
int molfile_ccp4plugin_init(void);
int molfile_ccp4plugin_register(void *,vmdplugin_register_cb);
int molfile_ccp4plugin_fini(void);
int molfile_corplugin_init(void);
int molfile_corplugin_register(void *,vmdplugin_register_cb);
int molfile_corplugin_fini(void);
int molfile_cpmdlogplugin_init(void);
int molfile_cpmdlogplugin_register(void *,vmdplugin_register_cb);
int molfile_cpmdlogplugin_fini(void);
int molfile_cpmdplugin_init(void);
int molfile_cpmdplugin_register(void *,vmdplugin_register_cb);
int molfile_cpmdplugin_fini(void);
int molfile_crdplugin_init(void);
int molfile_crdplugin_register(void *,vmdplugin_register_cb);
int molfile_crdplugin_fini(void);
int molfile_cubeplugin_init(void);
int molfile_cubeplugin_register(void *,vmdplugin_register_cb);
int molfile_cubeplugin_fini(void);
int molfile_dcdplugin_init(void);
int molfile_dcdplugin_register(void *,vmdplugin_register_cb);
int molfile_dcdplugin_fini(void);
int molfile_dlpolyplugin_init(void);
int molfile_dlpolyplugin_register(void *,vmdplugin_register_cb);
int molfile_dlpolyplugin_fini(void);
int molfile_dsn6plugin_init(void);
int molfile_dsn6plugin_register(void *,vmdplugin_register_cb);
int molfile_dsn6plugin_fini(void);
int molfile_dtrplugin_init(void);
int molfile_dtrplugin_register(void *,vmdplugin_register_cb);
int molfile_dtrplugin_fini(void);
int molfile_dxplugin_init(void);
int molfile_dxplugin_register(void *,vmdplugin_register_cb);
int molfile_dxplugin_fini(void);
int molfile_edmplugin_init(void);
int molfile_edmplugin_register(void *,vmdplugin_register_cb);
int molfile_edmplugin_fini(void);
int molfile_fs4plugin_init(void);
int molfile_fs4plugin_register(void *,vmdplugin_register_cb);
int molfile_fs4plugin_fini(void);
int molfile_gamessplugin_init(void);
int molfile_gamessplugin_register(void *,vmdplugin_register_cb);
int molfile_gamessplugin_fini(void);
int molfile_gaussianplugin_init(void);
int molfile_gaussianplugin_register(void *,vmdplugin_register_cb);
int molfile_gaussianplugin_fini(void);
int molfile_graspplugin_init(void);
int molfile_graspplugin_register(void *,vmdplugin_register_cb);
int molfile_graspplugin_fini(void);
int molfile_grdplugin_init(void);
int molfile_grdplugin_register(void *,vmdplugin_register_cb);
int molfile_grdplugin_fini(void);
int molfile_gridplugin_init(void);
int molfile_gridplugin_register(void *,vmdplugin_register_cb);
int molfile_gridplugin_fini(void);
int molfile_gromacsplugin_init(void);
int molfile_gromacsplugin_register(void *,vmdplugin_register_cb);
int molfile_gromacsplugin_fini(void);
int molfile_jsplugin_init(void);
int molfile_jsplugin_register(void *,vmdplugin_register_cb);
int molfile_jsplugin_fini(void);
int molfile_maeffplugin_init(void);
int molfile_maeffplugin_register(void *,vmdplugin_register_cb);
int molfile_maeffplugin_fini(void);
int molfile_mapplugin_init(void);
int molfile_mapplugin_register(void *,vmdplugin_register_cb);
int molfile_mapplugin_fini(void);
int molfile_mdfplugin_init(void);
int molfile_mdfplugin_register(void *,vmdplugin_register_cb);
int molfile_mdfplugin_fini(void);
int molfile_mmcif_init(void);
int molfile_mmcif_register(void *,vmdplugin_register_cb);
int molfile_mmcif_fini(void);
int molfile_mol2plugin_init(void);
int molfile_mol2plugin_register(void *,vmdplugin_register_cb);
int molfile_mol2plugin_fini(void);
int molfile_moldenplugin_init(void);
int molfile_moldenplugin_register(void *,vmdplugin_register_cb);
int molfile_moldenplugin_fini(void);
int molfile_msmsplugin_init(void);
int molfile_msmsplugin_register(void *,vmdplugin_register_cb);
int molfile_msmsplugin_fini(void);
int molfile_namdbinplugin_init(void);
int molfile_namdbinplugin_register(void *,vmdplugin_register_cb);
int molfile_namdbinplugin_fini(void);
int molfile_parm7plugin_init(void);
int molfile_parm7plugin_register(void *,vmdplugin_register_cb);
int molfile_parm7plugin_fini(void);
int molfile_parmplugin_init(void);
int molfile_parmplugin_register(void *,vmdplugin_register_cb);
int molfile_parmplugin_fini(void);
int molfile_pbeqplugin_init(void);
int molfile_pbeqplugin_register(void *,vmdplugin_register_cb);
int molfile_pbeqplugin_fini(void);
int molfile_pdbplugin_init(void);
int molfile_pdbplugin_register(void *,vmdplugin_register_cb);
int molfile_pdbplugin_fini(void);
int molfile_phiplugin_init(void);
int molfile_phiplugin_register(void *,vmdplugin_register_cb);
int molfile_phiplugin_fini(void);
int molfile_pltplugin_init(void);
int molfile_pltplugin_register(void *,vmdplugin_register_cb);
int molfile_pltplugin_fini(void);
int molfile_pqrplugin_init(void);
int molfile_pqrplugin_register(void *,vmdplugin_register_cb);
int molfile_pqrplugin_fini(void);
int molfile_psfplugin_init(void);
int molfile_psfplugin_register(void *,vmdplugin_register_cb);
int molfile_psfplugin_fini(void);
int molfile_raster3dplugin_init(void);
int molfile_raster3dplugin_register(void *,vmdplugin_register_cb);
int molfile_raster3dplugin_fini(void);
int molfile_rst7plugin_init(void);
int molfile_rst7plugin_register(void *,vmdplugin_register_cb);
int molfile_rst7plugin_fini(void);
int molfile_situsplugin_init(void);
int molfile_situsplugin_register(void *,vmdplugin_register_cb);
int molfile_situsplugin_fini(void);
int molfile_spiderplugin_init(void);
int molfile_spiderplugin_register(void *,vmdplugin_register_cb);
int molfile_spiderplugin_fini(void);
int molfile_stlplugin_init(void);
int molfile_stlplugin_register(void *,vmdplugin_register_cb);
int molfile_stlplugin_fini(void);
int molfile_tinkerplugin_init(void);
int molfile_tinkerplugin_register(void *,vmdplugin_register_cb);
int molfile_tinkerplugin_fini(void);
int molfile_uhbdplugin_init(void);
int molfile_uhbdplugin_register(void *,vmdplugin_register_cb);
int molfile_uhbdplugin_fini(void);
int molfile_vaspchgcarplugin_init(void);
int molfile_vaspchgcarplugin_register(void *,vmdplugin_register_cb);
int molfile_vaspchgcarplugin_fini(void);
int molfile_vaspoutcarplugin_init(void);
int molfile_vaspoutcarplugin_register(void *,vmdplugin_register_cb);
int molfile_vaspoutcarplugin_fini(void);
int molfile_vaspparchgplugin_init(void);
int molfile_vaspparchgplugin_register(void *,vmdplugin_register_cb);
int molfile_vaspparchgplugin_fini(void);
int molfile_vaspposcarplugin_init(void);
int molfile_vaspposcarplugin_register(void *,vmdplugin_register_cb);
int molfile_vaspposcarplugin_fini(void);
int molfile_vaspxdatcarplugin_init(void);
int molfile_vaspxdatcarplugin_register(void *,vmdplugin_register_cb);
int molfile_vaspxdatcarplugin_fini(void);
int molfile_vaspxmlplugin_init(void);
int molfile_vaspxmlplugin_register(void *,vmdplugin_register_cb);
int molfile_vaspxmlplugin_fini(void);
int molfile_vtfplugin_init(void);
int molfile_vtfplugin_register(void *,vmdplugin_register_cb);
int molfile_vtfplugin_fini(void);
int molfile_xbgfplugin_init(void);
int molfile_xbgfplugin_register(void *,vmdplugin_register_cb);
int molfile_xbgfplugin_fini(void);
int molfile_xsfplugin_init(void);
int molfile_xsfplugin_register(void *,vmdplugin_register_cb);
int molfile_xsfplugin_fini(void);
int molfile_xyzplugin_init(void);
int molfile_xyzplugin_register(void *,vmdplugin_register_cb);
int molfile_xyzplugin_fini(void);


    int PlugIOManagerRegister(PyMOLGlobals *G, vmdplugin_t *);

    int PlugIOManagerInitAll(PyMOLGlobals *G);

    int PlugIOManagerInitAll(PyMOLGlobals *G)
    {
       int ok=1;
    if(ok) ok = ok && (molfile_avsplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_basissetplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_basissetplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_bgfplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_binposplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_biomoccaplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_brixplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_carplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_ccp4plugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_corplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cpmdlogplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cpmdplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_crdplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cubeplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dcdplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dlpolyplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dsn6plugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dtrplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dxplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_edmplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_fs4plugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gamessplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gaussianplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_graspplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_grdplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gridplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gromacsplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_jsplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_maeffplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mapplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mdfplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mmcif_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mol2plugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_moldenplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_msmsplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_namdbinplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_parm7plugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_parmplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pbeqplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pdbplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_phiplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pltplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pqrplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_psfplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_raster3dplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_rst7plugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_situsplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_spiderplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_stlplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_tinkerplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_uhbdplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspchgcarplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspoutcarplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspparchgplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspposcarplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspxdatcarplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspxmlplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vtfplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xbgfplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xsfplugin_init() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xyzplugin_init() == VMDPLUGIN_SUCCESS);

       if(ok) {
    if(ok) ok = ok && (molfile_avsplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_basissetplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_basissetplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_bgfplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_binposplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_biomoccaplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_brixplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_carplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_ccp4plugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_corplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cpmdlogplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cpmdplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_crdplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cubeplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dcdplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dlpolyplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dsn6plugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dtrplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dxplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_edmplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_fs4plugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gamessplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gaussianplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_graspplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_grdplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gridplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gromacsplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_jsplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_maeffplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mapplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mdfplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mmcif_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mol2plugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_moldenplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_msmsplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_namdbinplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_parm7plugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_parmplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pbeqplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pdbplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_phiplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pltplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pqrplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_psfplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_raster3dplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_rst7plugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_situsplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_spiderplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_stlplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_tinkerplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_uhbdplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspchgcarplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspoutcarplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspparchgplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspposcarplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspxdatcarplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspxmlplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vtfplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xbgfplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xsfplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xyzplugin_register(G,(vmdplugin_register_cb)PlugIOManagerRegister) == VMDPLUGIN_SUCCESS);

       }
       return ok;
    }
    

    int PlugIOManagerRegister(PyMOLGlobals *G, vmdplugin_t *);

    int PlugIOManagerFreeAll(void);
    int PlugIOManagerFreeAll(void)
    {
       int ok=1;
    if(ok) ok = ok && (molfile_avsplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_basissetplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_basissetplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_bgfplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_binposplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_biomoccaplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_brixplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_carplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_ccp4plugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_corplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cpmdlogplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cpmdplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_crdplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_cubeplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dcdplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dlpolyplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dsn6plugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dtrplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_dxplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_edmplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_fs4plugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gamessplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gaussianplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_graspplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_grdplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gridplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_gromacsplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_jsplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_maeffplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mapplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mdfplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mmcif_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_mol2plugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_moldenplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_msmsplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_namdbinplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_parm7plugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_parmplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pbeqplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pdbplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_phiplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pltplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_pqrplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_psfplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_raster3dplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_rst7plugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_situsplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_spiderplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_stlplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_tinkerplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_uhbdplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspchgcarplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspoutcarplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspparchgplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspposcarplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspxdatcarplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vaspxmlplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_vtfplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xbgfplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xsfplugin_fini() == VMDPLUGIN_SUCCESS);
if(ok) ok = ok && (molfile_xyzplugin_fini() == VMDPLUGIN_SUCCESS);

       return ok;
    }
