target_sources(${TARGET_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}/AssemblyHelpers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AtomInfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AtomInfoHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/BondTypeHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CifFile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CifMoleculeReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/CoordSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DistSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/GadgetSet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HydrogenAdder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MmodTyping.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MmtfMoleculeReader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Mol2Typing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MolV3000.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectAlignment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectCallback.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectCGO.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectCurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectDist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectGadget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectGadgetRamp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectGroup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectMap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectMesh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectMolecule.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectMolecule2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectMolecule3.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectSlice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectSurface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ObjectVolume.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepAngle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepCartoon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepCylBond.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepDihedral.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepDistDash.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepDistLabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepDot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepEllipsoid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepLabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepMesh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepNonbonded.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepNonbondedSphere.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepRibbon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepSphere.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepSphereGenerate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepSphereImmediate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepSurface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RepWireBond.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Sculpt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SculptCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SideChainHelper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/VFont.cpp
)

target_include_directories(${TARGET_NAME} PUBLIC
    ${CMAKE_CURRENT_LIST_DIR}
)
